config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|vi/ do
    devise_for :users
    root "airports#index"
    resources :airports do
      collection do
        get 'search'
      end
      resources :reviews, except: [:index, :show]
    end

    get 'pages/about'
    get 'pages/contact'
  end

end

app/models/airport.rb
class Airport < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  searchkick

  has_many :reviews

  validates :name, presence: true, uniqueness: true
  validates :city, presence: true
  validates :IATA, presence: true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :airport

  validates :rating, presence: true, numericality: true, inclusion: { in: 1..5, message: 'must be between 1-5' }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reviews, dependent: :destroy #To delete all reviews associated with a particular user when that user account is deleted

  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
  before_action :set_airport, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index,:search, :show]
  before_action :check_user, except: [:index, :search, :show]
  # GET /airports
  # GET /airports.json
  def search
    if params[:search].present?
      @airports = Airport.search(params[:search])
    else
      @airports = Airport.all
    end
  end

  def index
    @airports = Airport.all
  end

  # GET /airports/1
  # GET /airports/1.json
  def show
    @all_reviews = Review.where(airport_id: @airport.id)
    @reviews = Review.where(airport_id: @airport.id).order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
    if @all_reviews.blank?
      @avg_rating = 0
    else
      @avg_rating = @all_reviews.average(:rating)
    end
  end

  def new
    @airport = Airport.new
  end

  # GET /airports/1/edit
  def edit
  end

  # POST /airports
  # POST /airports.json
  def create
    @airport = Airport.new(airport_params)

    respond_to do |format|
      if @airport.save
        format.html { redirect_to root_path, notice: 'Airport was successfully created.' }
        format.json { render :show, status: :created, location: @airport }
      else
        format.html { render :new }
        format.json { render json: @airport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /airports/1
  # PATCH/PUT /airports/1.json
  def update
    respond_to do |format|
      if @airport.update(airport_params)
        format.html { redirect_to @airport, notice: 'Airport was successfully updated.' }
        format.json { render :show, status: :ok, location: @airport }
      else
        format.html { render :edit }
        format.json { render json: @airport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airports/1
  # DELETE /airports/1.json
  def destroy
    @airport.destroy
    respond_to do |format|
      format.html { redirect_to airports_url, notice: 'Airport was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_airport
      @airport = Airport.find(params[:id])
    end

    def check_user
      unless current_user.admin?
        redirect_to root_path, alert: "This action is restricted to admin only"
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def airport_params
      params.require(:airport).permit(:name, :city, :IATA, :image, :website)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options = {})
    { locale: I18n.locale }
  end

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name
    devise_parameter_sanitizer.for(:sign_up) << :last_name
    devise_parameter_sanitizer.for(:account_update) << :first_name
    devise_parameter_sanitizer.for(:account_update) << :last_name
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:edit, :update, :destroy]
  before_action :set_airport
  before_action :authenticate_user!
  before_action :check_user, only: [:edit, :update, :destroy]

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.airport_id = @airport.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to airport_path(@airport), notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to airport_path(@airport), notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to airport_path(@airport), notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_review
      @review = Review.find(params[:id])
    end

    def set_airport
      @airport = Airport.find(params[:airport_id])
    end

    def check_user
      unless (@review.user == current_user) || (current_user.admin?)
        redirect_to root_path, alert: "This review cannot be changed or deleted because it belongs to someone else"
      end
    end

    def review_params
      params.require(:review).permit(:rating, :description)
    end
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span>
      </button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/airports/_form.html.erb
<%= form_for(@airport, :html => { multipart: true }) do |f| %>
  <% if @airport.errors.any? %>
    <div id="error_explanation" class="alert alert-warning alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4><%= pluralize(@airport.errors.count, "error") %> prohibited this airport from being saved:</h4>
      <ul>
      <% @airport.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :city %><br>
    <%= f.text_field :city, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :IATA %><br>
    <%= f.text_field :IATA, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :website %><br>
    <%= f.text_field :website, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-info btn-lg" %>
  </div>
<% end %>

app/views/airports/edit.html.erb
<h1>Editing Airport</h1>

<%= render 'form' %>

<%= link_to 'Show', @airport, class: "btn btn-link" %> |
<%= link_to 'Back', airports_path, class: "btn btn-link" %>

app/views/airports/index.html.erb
<div class="jumbotron">
  <!-- replace text with translation -->
  <%= t('jumbotron_title_html') %>
  <%= t('jumbotron_subtitle_html') %>
</div>
<table class="table table-hover">
  <thead>
    <tr>
      <%= t('name_html') %>
      <%= t('city_html') %>
      <%= t('iata_html') %>
      <% if user_signed_in? && current_user.admin? %>
        <th colspan="2"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @airports.each do |airport| %>
      <tr>
        <td><%= link_to airport.name, airport_path(airport) %></td>
        <td><%= airport.city %></td>
        <td><%= airport.IATA %></td>
        <% if user_signed_in? && current_user.admin? %>
          <td><%= link_to 'Edit', edit_airport_path(airport), class: "btn btn-link" %></td>
          <td><%= link_to 'Destroy', airport, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
  <% if user_signed_in? && current_user.admin? %>
    <%= link_to 'New Airport', new_airport_path, class: "btn btn-link" %>
  <% end %>

app/views/airports/new.html.erb
<h1>New Airport</h1>

<%= render 'form' %>

<%= link_to 'Back', airports_path, class: "btn btn-link" %>

app/views/airports/search.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th>IATA</th>
      <% if user_signed_in? && current_user.admin? %>
        <th colspan="2"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @airports.each do |airport| %>
      <tr>
        <td><%= link_to airport.name, airport_path(airport) %></td>
        <td><%= airport.city %></td>
        <td><%= airport.IATA %></td>
        <% if user_signed_in? && current_user.admin? %>
          <td><%= link_to 'Edit', edit_airport_path(airport), class: "btn btn-link" %></td>
          <td><%= link_to 'Destroy', airport, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/airports/show.html.erb
<div class="row">
  <div class="col-md-5">
    <%= image_tag @airport.image_url %>

    <h2>
      <%= @airport.name %>
    </h2>

    <div class="star-rating" data-score= <%= @avg_rating %> ></div>
    <p><%= "#{@all_reviews.length} reviews" %></p>
    <p>
      <strong>City:</strong>
      <%= @airport.city %>
    </p>

    <p>
      <strong>IATA:</strong>
      <%= @airport.IATA %>
    </p>

    <p>
      <% if @airport.website.blank? %>
        <strong>Website:</strong> Not Available
      <% else %>
        <strong>Website:</strong>
        <br>
        <a id="website" href="http://www.flychicago.com/Ohare/OhareHomepage.shtm"><%= @airport.website %></a>
      <% end %>
    </p>

    <%= link_to "Add a Review", new_airport_review_path(@airport), class: "btn btn-info btn-lg" %>

    <br>
    <br>

    <iframe
      width="240"
      height="230"
      frameborder="0" style="border:0"
      src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCaW9lJ26cwuwS4yEac_ZboyiID-F_3LLE
        &q=<%= @airport.name %>&zoom=10" allowfullscreen>
      </iframe>
  </div>

  <div class="col-md-7">
    <% if @reviews.blank? %>
      <h3>No Reviews Yet. Be the first to write one!</h3>
    <% else %>
      <table class="table">
        <thead>
          <tr>
            <th class="col-md-3"></th>
            <th class="col-md-9"></th>
          </tr>
        </thead>
        <tbody>
          <% @reviews.each do |review| %>
            <tr>
              <td>
                <h4><%= "#{review.user.first_name.capitalize} #{review.user.last_name.capitalize[0]}." %></h4>
                <p><%= review.created_at.strftime("%-m/%-d/%y") %></p>
              </td>
              <td>
                <div class="star-rating" data-score= <%= review.rating %> ></div>
                <p><%= h(review.description).gsub(/\n/, '<br/>').html_safe %></p>
                <% if user_signed_in? %>
                  <% if (review.user == current_user) || (current_user.admin?) %>
                    <%= link_to "Edit", edit_airport_review_path(@airport, review), id: "edit-link"%>
                    <%= link_to "Delete", airport_review_path(@airport, review), method: :delete %>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
    <br>
    <%= will_paginate @reviews %>
  </div>
</div>

<%= link_to 'Edit', edit_airport_path(@airport), class: "btn btn-link" %> |
<%= link_to 'Back', airports_path, class: "btn btn-link" %>

<script>
  $('.star-rating').raty({
    path: 'https://s3.amazonaws.com/airport-reviews/stars',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>

app/views/layouts/_footer.html.erb
<div class="footer">
  <p>When in doubt, travel!</p>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-inverse">
<div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "IntelliFly", root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li><%= link_to t('about'), pages_about_path %></li>
      <li><%= link_to t('contact'), pages_contact_path %></li>
    </ul>
    <!-- replace default search field came with bootstaps with custom one that goes with searchkick -->
    <%= form_tag search_airports_path, method: :get, class: "navbar-form navbar-left" do %>
      <p>
        <%= text_field_tag :search, params[:search], class: "form-control", placeholder: t('lets_find_your_airport') %>
        <%= submit_tag t('search'), name: nil, class: "btn btn-default" %>
      </p>
    <% end %>
    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
         <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Language <b class="caret"></b></a>
         <ul class="dropdown-menu">
           <li><%= link_to t('english'), root_path(locale: 'en') %></li>
           <li><%= link_to t('vietnamese'), root_path(locale: 'vi') %></li>
         </ul>
       </li>
      <% if user_signed_in? %>
        <li><%= link_to t('edit_profile'), edit_user_registration_path %></li>
        <li><%= link_to t('sign_out'), destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to t('sign_up'), new_user_registration_path %></li>
        <li><%= link_to t('sign_in'), new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>IntelliFly</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
  <!-- Latest compiled and minified JQuery -->
  <link href='https://fonts.googleapis.com/css?family=Alex+Brush' rel='stylesheet' type='text/css'>
  <script src="//code.jquery.com/jquery-2.1.1.min.js"></script>
   <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <script src="https://www.google.com/jsapi"></script>
  <script src="http://www.google.com/uds/solutions/dynamicfeed/gfdynamicfeedcontrol.js"
  type="text/javascript"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>
  <div class="container-fluid">
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissable">
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
      <% end %>
    <% end %>

    <%= yield %>

    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/pages/about.html.erb
<%= t('about_page_greeting_html') %>
<%= t('about_page_content_html') %>

app/views/pages/contact.html.erb
<h1>Let's connect!</h1>
<br>
<p>Find me here on:</p>
  <ul>
    <li><a href="https://www.linkedin.com/in/nganvien">Linkedin</a></li>
    <li><a href="https://github.com/nvien">GitHub</a></li>
  </ul>
<br>

app/views/reviews/_form.html.erb
<%= form_for([@airport, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation" class="alert alert-warning alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h4>
      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="star-rating"></div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-info btn-lg" %>
  </div>
<% end %>

<script>
  $('#star-rating').raty({
    path: 'https://s3.amazonaws.com/airport-reviews/stars',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Back', airport_path(@airport) %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', airport_path(@airport) %>